# -*- coding: utf-8 -*-
"""Copia de Progra_Avanzada_Entrega_Parcial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nw90hU8dRZH6c0sBcKlkYUyWlDfk3OS
"""

import pandas as pd


df = pd.read_excel("/content/BBDD ONSV - PERSONAS 2021-2023.xlsx", header=3)

df.head()

df.info()

"""# Manejo de Nulos

La columna 'POSEE LICENCIA' tiene varios valores nulos, pero 'ESTADO LICENCIA' no; nos guiaremos por esta última
"""

df.drop('POSEE LICENCIA', axis=1, inplace=True)

"""Como solo existen 19 registros que no cuentan con información en 'VEHÍCULO', se eliminarán estos registros."""

df.dropna(subset=['VEHÍCULO'], inplace=True)
df.info()

"""En el caso de 'LUGAR ATENCIÓN LESIONADO' y 'LUGAR DE DEFUNCIÓN', se reemplazarán los valores nulos acorde a la gravedad"""

df.loc[df['GRAVEDAD']=="LESIONADO", 'LUGAR ATENCIÓN LESIONADO'] = df.loc[df['GRAVEDAD']=="LESIONADO", 'LUGAR ATENCIÓN LESIONADO'].fillna("SIN INFORMACIÓN")
df['LUGAR ATENCIÓN LESIONADO'] = df['LUGAR ATENCIÓN LESIONADO'].fillna("NO SE ENCONTRABA LESIONADO")

df.loc[df['GRAVEDAD']=="FALLECIDO", 'LUGAR DE DEFUNCIÓN'] = df.loc[df['GRAVEDAD']=="FALLECIDO", 'LUGAR DE DEFUNCIÓN'].fillna("SIN INFORMACIÓN")
df['LUGAR DE DEFUNCIÓN'] = df['LUGAR DE DEFUNCIÓN'].fillna("NO HA FALLECIDO")
df.info()

"""Para el caso de nacionalidad, se reemplazará los valores nulos por 'SIN INFORMACIÓN' para los gráficos."""

df['PAÍS DE NACIONALIDAD'] = df['PAÍS DE NACIONALIDAD'].fillna("SIN INFORMACIÓN")
df.info()

"""Para el caso de otra nacionalidad, se reemplazará los valores nulos por 'SIN INFORMACIÓN' cuando la nacionalidad no es peruana."""

df.loc[df['PAÍS DE NACIONALIDAD']!='PERÚ', 'OTRO PAÍS DE NACIONALIDAD'] = df.loc[df['PAÍS DE NACIONALIDAD']!='PERÚ', 'OTRO PAÍS DE NACIONALIDAD'].fillna("SIN INFORMACIÓN")
df.info()

"""En el caso de '¿SE SOMETIÓ A DOSAJE ETÍLICO CUALITATIVO?', se reemplazará los nulos por 'SIN INFORMACIÓN' cuando tampoco hay información en el resultado.

# PREGUNTAR SI PODEMOS LLENARLO CON NO
"""

df.loc[~df['RESULTADO DEL DOSAJE ETÍLICO CUALITATIVO'].isna(), '¿SE SOMETIÓ A DOSAJE ETÍLICO CUALITATIVO?'] = df.loc[~df['RESULTADO DEL DOSAJE ETÍLICO CUALITATIVO'].isna(), '¿SE SOMETIÓ A DOSAJE ETÍLICO CUALITATIVO?'].fillna("SI")
df['¿SE SOMETIÓ A DOSAJE ETÍLICO CUALITATIVO?'] = df['¿SE SOMETIÓ A DOSAJE ETÍLICO CUALITATIVO?'].fillna("SIN INFORMACIÓN")
df.info()

"""En el caso del resultado del dosaje etílico cualitativo, solo se rellenará los nulos cuando se hizo el dosaje."""

df.loc[df['¿SE SOMETIÓ A DOSAJE ETÍLICO CUALITATIVO?']=='SI', 'RESULTADO DEL DOSAJE ETÍLICO CUALITATIVO'] = df.loc[df['¿SE SOMETIÓ A DOSAJE ETÍLICO CUALITATIVO?']=='SI', 'RESULTADO DEL DOSAJE ETÍLICO CUALITATIVO'].fillna("NO REGISTRADO")
df.info()

"""Como no se tiene el resultado del dosaje etílico cuantitativo saber si se realizó el dosaje no será relevante para este análisis."""

df.drop('¿SE SOMETIÓ A DOSAJE ETÍLICO CUANTITATIVO?', axis=1, inplace=True)
df.info()

"""# Otro Procesamiento de Datos

Irregularidades en los datos de 'OTRO PAÍS DE NACIONALIDAD'
"""

sorted(df['OTRO PAÍS DE NACIONALIDAD'].unique(), key=lambda x: str(x))

df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['-', '.-------------', 'CONDUCTOR FUGADO', 'CONDUCTOR NO IDENTICADO', 'DESCONOCIDO', 'EXTRANJERO ', 'FUGA', 'FUGADO', 'NN', 'NO EXISTE CONDUCTOR', 'NO IDENTIFICADO', 'NO INDICA', 'NO SE CONOCE', 'NO SE CONOCE POR FUGA', 'NO SE IDENTIFICA', 'NO SE IDENTIFICÓ', 'SE DESCONOCE', 'SE DESCONOCE ', 'SE DESCONOCE POR FUGA', 'SE DESCONOCE, TODA VEZ QUE EL VEHICULO SE DIO A LA FUGA ', 'SE DESCONOSE', 'SIN IDENTIFICAR'], "SIN INFORMACIÓN")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['ARGERTINA'], "ARGENTINA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['BOLIVIA ', 'BOLIVIANA', 'BOLIVIANO'], "BOLIVIA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['BRASILEÑA'], "BRASIL")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['BRITANICO '], "REINO UNIDO")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['CHILENA', 'CHILENO'], "CHILE")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['COLOMBIA ', 'COLOMBIANA', 'COLOMBIANO', 'COLOMBIANO '], "COLOMBIA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['ECUADOR ', 'ECUATORIANO', 'ECUATORIANO '], "ECUADOR")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['FRANCES'], "FRANCIA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['ITALIANO'], "ITALIA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['ALEMANA'], "ALEMANIA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['CANADA'], "CÁNADA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['HAITIANO'], "HAITÍ")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['HOLANDA'], "PAÍSES BAJOS")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['REPUBLICA CHECA'], "REPÚBLICA CHECA")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['MEJICO', 'MEXICANO', 'MEXICO'], "MÉXICO")
df['OTRO PAÍS DE NACIONALIDAD'] = df['OTRO PAÍS DE NACIONALIDAD'].replace(['VELEZOLANO', 'VENENZUELA', 'VENEOZOLANA ', 'VENEZIUELA', 'VENEZOLANA', 'VENEZOLANO', 'VENEZOLANO ', 'VENEZONALA ', 'VENEZUELA ', 'VENZUELA', 'VFENEZOLANO'], "VENEZUELA")


sorted(df['OTRO PAÍS DE NACIONALIDAD'].unique(), key=lambda x: str(x))
